services:
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./websites:/websites
    ports:
      - "8000:8000"

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: v.je
      MYSQL_USER: v.je
      MYSQL_PASSWORD: v.je
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3308:3306"

volumes:
  mysqldata: {}
